[package]
name = "tty-form"
description = "A generic framework for building multi-step forms atop TTY-based interfaces."
version = "0.1.0"
authors = ["Daniel Way <contact@danieldway.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/danielway/tty-form"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
tty-interface = "2.0.0"
